config/routes.rb
Rails.application.routes.draw do
  post 'add/user', to: 'rooms#add_user'
  resources :rooms
  devise_for :users
  root 'rooms#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  has_many :user_rooms
  has_many :users, through: :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_rooms
  has_many :rooms, through: :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: %i[show edit update destroy]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit; end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        UserRoom.create(room: @room, user: current_user)
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('room', partial: 'shared/room', locals: { room: @room })
        end
      else
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('room_form', partial: 'rooms/form', locals: { room: @room })
        end
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update room_params
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("room_#{@room.id}", partial: 'shared/room', locals: { room: @room })
        end
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!
  end

  def add_user
    UserRoom.create(room_id: params[:room_id], user_id: params[:user_id])

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("room_show_#{params[:room_id]}", partial: 'rooms/room',
                                                                                   locals: { room: Room.find(params[:room_id]) })
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "flex flex-col my-3 w-full") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>
      <ul class="list-disc ml-6">
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col gap-1 justify-center">
    <%= form.label :name, class: 'text-white font-semibold text-sm' %>
    <%= form.text_field :name, class: 'w-full rounded border border-gray-200 font-semibold text-xs' %>
  </div>
  <div class="flex mt-2 gap-2 justify-end">
    <%= form.submit class: "p-2 text-sm text-white font-semibold bg-green-600 rounded cursor-pointer" %>
    <%= link_to 'Cancel', :back, class: 'p-2 text-sm text-white font-semibold bg-red-600 rounded cursor-pointer' %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<section class="flex flex-col gap-2 mt-10 items-center justify-center" id="room_show_<%= "#{room.id}" %>">
  <div class="flex flex-col">
    <h3 class="font-bold text-3xl text-white"><%= room.name %> - Room</h3>
    <span class="text-white font-semibold">Users in this room: </span>
  </div>
  <section class="flex gap-5">
    <div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-lg my-2 shadow-lg w-96">
      <h3 class="text-white font-semibold text-center">Users in this room</h3>
      <% User.all.each do |user| %>
        <% next unless room.users.include?(user)%>
        <div class="rounded underline text-white my-1 font-semibold text-sm">
          <%= user.email %>
        </div>
      <% end %>
    </div>
    <div class="py-2 px-10 flex flex-col gap-1 items-center border-sky-600 border rounded-lg my-2 shadow-lg w-96">
      <h3 class="text-white font-semibold text-center">Add users</h3>
      <% User.all.each do |user| %>
        <% next if room.users.include?(user)%>
        <%= button_to add_user_path, params: { user_id: user, room_id: room }, id: "add_user_#{user.id}", method: :post do %>
          <div class="rounded underline text-white my-1 font-semibold text-sm">
            <%= user.email %>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</section>

app/views/rooms/edit.html.erb
<%= turbo_frame_tag "room_#{@room.id}" do %>
  <h4 class="font-medium text-base text-white text-center">Edit room</h4>
  <%= render 'form', room: @room %>
<% end %>

app/views/rooms/index.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
  <main class="flex w-full h-screen bg-slate-800">
    <%= render 'shared/sidebar' %>
    <section class="flex flex-col items-center justify-center gap-5 h-screen w-full">
      <%= image_tag('chat.png', width: 100) %>
      <h1 class="font-bold text-4xl text-white my-4">Chat App built with Ruby</h1>
      <p class="text-center font-semibold text-white">This is an app created that uses RoR</p>
    </section>
  </main>
<% end %>

app/views/rooms/new.html.erb
<%= turbo_frame_tag 'room_form' do %>
  <h4 class="font-medium text-base text-white text-center">Create new room</h4>
  <%= render "form", room: @room %>
<% end %>

app/views/rooms/show.html.erb
<%= turbo_frame_tag 'rooms_controller' do %>
  <main class="flex w-full h-screen bg-slate-800">
    <%= render 'shared/sidebar' %>
    <section class="w-5/6 flex flex-col gap-5 h-screen px-5">
      <%= render 'room', room: @room %>
    </section>
  </main>
<% end %>

app/views/shared/_create_room.html.erb
<%= turbo_frame_tag 'room_form' do %>
  <section class="flex flex-col items-center justify-center gap-2 mb-5">
    <h3 class="text-white font-semibold text-sm text-center">Start a new conversation</h3>
    <%= link_to new_room_path, id: 'new_room', class: 'px-3 py-1 bg-green-700 text-white font-semibold text-sm' do %>
      Create new room
    <% end %>
  </section>
<% end %>

app/views/shared/_room.html.erb
<%= turbo_frame_tag "room_#{room.id}" do %>
  <div class="text-white font-semibold">
    <%= link_to room_path(room), class: 'font-semibold text-white text-sm', data: { turbo_frame: 'rooms_controller' } do %>
      <%= room.name %>
    <% end %>
    <%= link_to 'Edit room', edit_room_path(room) %>
  </div>
<% end %>

app/views/shared/_sidebar.html.erb
<nav class="w-60 flex flex-col items-center justify-between border border-sky-500">
  <%= render 'shared/user_rooms' %>
  <%= render 'shared/create_room' %>
</nav>

app/views/shared/_user_rooms.html.erb
<section class="flex flex-col w-full">
  <span class="text-white text-center font-semibold mt-5"><%= current_user.email %></span>
  <div class="flex items-center justify-center mt-2"><%= button_to 'Log out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'px-3 py-1 text-white bg-red-700 rounded font-semibold text-sm' %></div>
  <h3 class="text-white font-bold text-xl mt-3 text-center mb-2">My rooms</h3>
  <div class="flex flex-col px-5 gap-2 w-full" id="rooms">
    <% current_user.rooms.all.each do |room| %>
      <%= render 'shared/room', { room: room } %>
    <% end %>
  </div>
</section>